### ISSUE TITLE
Transit details issue

### ISSUE THREAD

**Issue by Alexandru-C** [marchdev-tk/google_directions_api#12]
**Steps to Reproduce**

1. Trying to get the transit details in travelMode transit.

**The issue:** The issue is in the *factory Step.fromMap(Map<String, dynamic> map)* method, at line 799 in *directions.response.dart*. At the transit named parameter it checks whether map['transit'] is null or not, but *transit* is not the right key to look for.

**How to fix the issue:** Change *map['transit']* with *map['transit_details']* and it will work fine.  

**Additional details** I am using version 0.9.1 of the google_directions_api

**Comment by OlehMarch** [comment]
Will be fixed in 0.10.0
