### ISSUE TITLE
Dependancy  Incompatible

### ISSUE THREAD

**Issue by axelasa** [marchdev-tk/google_directions_api#16]
dart pub add google_directions_api  
The current Dart SDK version is 3.2.0.

Because google_directions_api <0.6.0 doesn't support null safety and google_directions_api >=0.6.0 <0.8.0 depends on http ^0.13.0, google_directions_api <0.8.0
  requires http ^0.13.0.
And because google_directions_api >=0.8.0 <0.9.1 depends on http ^0.13.1, google_directions_api <0.9.1 requires http ^0.13.0.
And because google_directions_api >=0.9.1 depends on http ^0.13.4 and flutter_polyline_points >=2.0.0 depends on http ^1.0.0, flutter_polyline_points >=2.0.0 is
  incompatible with google_directions_api.
So, because live_location_tracker depends on both flutter_polyline_points ^2.0.0 and google_directions_api any, version solving failed.

The lower bound of "sdk: '>=2.6.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

# recreate  ->

run :  dart pub add google_directions_api  on Dart SDK version is 3 and above. to get the error.

**Comment by OlehMarch** [comment]
Will be fixed in 0.10.0
