### ISSUE TITLE
Web: directions requests blocked by CORS

### ISSUE THREAD

**Issue by cedrichansen** [marchdev-tk/google_directions_api#2]
According to what I see on pub.dev, this package should be functional on web, however, this does not seem to be the case.

![image](https://user-images.githubusercontent.com/28404014/97093151-954f6780-1617-11eb-8d3d-592427b5a2bb.png)

I get the following CORS error, 
```
Access to XMLHttpRequest at 'https://maps.googleapis.com/maps/api/directions/json?.....' from origin 'http://localhost:49564' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Which is expected upon reading some of the google directions docs.
My application/directions requests work very well on android/ios.

If this package does not work for web, the 'web' label should be removed from the pub site.

If there is a workaround for web, any help/guidance would be appreciated!

**Comment by ozz-rjq** [comment]
did you find a solution?

**Comment by cedrichansen** [comment]
I created a micro service (in golang). The service listens for http requests that contains the list of addresses I wish to get directions for (plus some other meta data). The service makes the directions request, and then returns the poly line and info about time/distance to the client, and the client is able to render the poly line on a map without any issue. This doesn't actually fix the fact that this package doesn't work on web, but the workaround works just fine (and is probably even a better idea in all honesty - can hide my api keys on a server). Hope this helps!

**Comment by OlehMarch** [comment]
It seems that calls to https from http source is not valid anymore, it should be fixed via transfering app to https
