### ISSUE TITLE
Http.get method changed to take Uri. 

### ISSUE THREAD

**Issue by gustav3d** [marchdev-tk/google_directions_api#4]
http package changed:
https://github.com/dart-lang/http/pull/507

../../.pub-cache/hosted/pub.dartlang.org/google_directions_api-0.5.0/lib/src/directions.dart:55:37: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    final response = await http.get(url);

**Comment by OlehMarch** [comment]
Solved since 0.6.0 version
