### ISSUE TITLE
waypoint_order always returned null

### ISSUE THREAD

**Issue by rxviperx** [marchdev-tk/google_directions_api#5]
Hi,

I couldn't get waypointOrder data result returned from google direction api.
Below is the request that I sent over. I've make sure that my google API key is correct, I can get DirectionsStatus status = success.
I've set the optimize = true, and are hoping to get some data returned as per API, but it somehow gaves me null result.
From API I'm expecting something like : "waypoint_order": [ 3, 2, 0, 1 ]
I wanted to use this to pass over few location (placeID) and hoping google API to returned me the most optimized point which should be the first point to go until the end

?origin=place_id:ChIJlcdulQBLzDERqjl_67bNUYQ&destination=place_id:ChIJD3VG5wNLzDERJp0g1KY-FN0&mode=driving&waypoints=optimize:true|place_id:ChIJ8UzLwUZKzDERAO-5xB4S_SY|place_id:ChIJL-Qvn9JOzDERBLmeTTrrgf0

![image](https://user-images.githubusercontent.com/34273737/105804323-7b3c7100-5fda-11eb-9b19-66bf27047c4c.png)

Hope you're able to shed some light to me.

Regards,
Brian

**Comment by ghost** [comment]
@rxviperx did you find a solution or workaround?

**Comment by ancileddu** [comment]
Hi all, maps directions api return a list called "waypoint_order". in DirectionsRoute model is decoded "map['waypointOrder'] as List" instead map['waypoint_order'] as List. Please fix it. Thanks

**Comment by OlehMarch** [comment]
Fixed since 0.8.0 version
