### ISSUE TITLE
Misnaming duration_in_trafic

### ISSUE THREAD

**Issue by metehanpinarli** [marchdev-tk/google_directions_api#8]
The naming in the code is wrong. Needs to be fixed urgently
![duration_in_trafic](https://user-images.githubusercontent.com/56471014/145825833-59bf9f3f-2047-4d58-b01a-b19637da3abf.png)
![duration_in_traffic](https://user-images.githubusercontent.com/56471014/145825837-f895325a-5c1e-477e-9911-0686ae49296c.png)

**Comment by OlehMarch** [comment]
Thanks for pointing to this issue, fix will be in the next update (0.9.1)
