### ISSUE TITLE
map['value'] in Time.fromMap is an int not string in directions.response.dart

### ISSUE THREAD

**Issue by willcalderbank** [marchdev-tk/google_directions_api#9]
Hi,

When running on iOS the value in map['value'] is an int not a string in directions.response.dart and therefore `map['value'] as String` fails.

Ive noticed this only occurs when querying for transit directions.

![Screenshot 2022-05-27 at 15 18 59](https://user-images.githubusercontent.com/1479080/170717863-6fa948c5-ccc2-48be-b4a9-09ee810d0526.png)

**Comment by OlehMarch** [comment]
Will be fixed in 0.10.0
